{"traceback": "Traceback (most recent call last):\n  File \"/Users/petercotton/github/precise/precise/skaters/managerutil/managertesting.py\", line 21, in manager_test_run\n    w, s = mgr(y=y, s=s, e=-1)\n  File \"/Users/petercotton/github/precise/precise/skaters/managers/rplhrpmanagers.py\", line 56, in rpl_hrp_var_long_manager_n200\n    return rpl_hrp_factory(y=y, s=s, k=k, e=e, metric='VaR', n_buffer=200)\n  File \"/Users/petercotton/github/precise/precise/skaters/managers/rplmanagerfactory.py\", line 21, in rpl_hrp_factory\n    return rpl_manager_factory(s=s, y=y, k=k, cls_name='HCPortfolio', n_buffer=n_buffer, optim_kwargs=optim_kwargs)\n  File \"/Users/petercotton/github/precise/precise/skaters/managers/rplmanagerfactory.py\", line 30, in rpl_manager_factory\n    s = _buf(funcs=[_rpl_func], func_names=['weights'], func_kwargs=[fun_kwargs], s=s, x=y,\n  File \"/Users/petercotton/github/precise/precise/skaters/covariance/buffactory.py\", line 74, in _buf\n    s = _buf_update(funcs=funcs, func_names=func_names, func_kwargs=func_kwargs, s=s, x=x, n_buffer=n_buffer, e=e)\n  File \"/Users/petercotton/github/precise/precise/skaters/covariance/buffactory.py\", line 95, in _buf_update\n    s[func_name] = func(s['buffer'],**func_kwargs)\nTypeError: _rpl_func() got an unexpected keyword argument 'cls_name'\n", "exception": "_rpl_func() got an unexpected keyword argument 'cls_name'", "manager": "rpl_hrp_var_long_manager_n200"}